config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
  get '/about' => 'home#about', as: :about

  resources :users, only: [:new, :create, :edit, :update] do
    resources :favourites, only: :index
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :posts do
    resources :comments do
    end
    resources :favourites, only: [:create, :destroy, :index]
  end



end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user  ||= User.new

    can :manage, Post do |post|
      post.user == user
    end

    can :delete, Comment do |comment|
      comment.user == user || comment.post.user
    end

    can :favourite, Post do |post|
      post.user != user
    end

    cannot :favourite, Post do |post|
      post.user == user
    end

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many    :posts,  dependent: :nullify
  belongs_to  :user

  validates :title, presence: true,
                    uniqueness: true;
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body,  presence: true,
                    uniqueness: { scope: :post}

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true,
                      uniqueness: {scope: :post_id}

  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord


  has_many :comments, -> {order(created_at: :desc)}, :dependent => :destroy
  has_many :favourites, dependent: :destroy
  has_many :favouriters, through: :favourites, source: :user

  belongs_to :category
  belongs_to :user



  validates :title, presence: true,
                    uniqueness: true

  validates :body, presence: true

  def self.search(search)
    if search
      Post.all.where( "title ILIKE ? OR body ILIKE ?",
                      "%#{search}%",
                      "%#{search}%").order(created_at: :desc)
    else
      Post.all.order(created_at: :desc)
    end
  end

  def like_for(user)
    favourites.find_by(user: user)
  end

  


end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts,    dependent: :nullify
  has_many :comments, dependent: :nullify

  has_many :favourites, dependent: :destroy
  has_many :favourited_products, through: :favourites, source: :post

  validates :first_name,  presence: true
  validates :last_name,   presence: true
  validates :email,       presence: true,
                          uniqueness: true
  has_secure_password

  def get_full_name
    "#{first_name} #{last_name}".titleize
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user, only: [:create, :destroy]

  def create
    @post               = Post.find params[:post_id]
    @comment_params     = params.require(:comment).permit(:body)
    @comment            = Comment.new @comment_params
    @comment.post       = @post
    @comment.user       = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end


  end

  def destroy
    @comment=params[:id]
    @post=@comment.post
    @comment.destroy
    redirect_to post_path(@post)
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  before_action :authenticate_user

  def create

    @post       = Post.find(params[:post_id])
    @favourite  = Favourite.new(user: current_user, post: @post)

    if @favourite.save
      redirect_to post_path(@post), notice: "yas"
    else
      redirect_to post_path(@post), notice: "nas"
    end
  end

  def destroy

    @favourite  = Favourite.find(params[:id])
    @post       = @favourite.post

    if @favourite.destroy
      redirect_to post_path(@post), notice: "🗿"
    else
      redirect_to post_path(@post), notice: ""
    end

  end

  def index
    @favourites = User.find(params[:user_id]).favourites.page(params[:page]).per(10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authorize_access, only: [:edit, :update, :destroy]
  before_action :get_post, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user, except: [:index, :show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params(params)

    @post.user = current_user

    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end

  end

  def index
    @posts = Post.search(params[:search]).page(params[:page]).per(10)
  end

  def edit
    redirect_to post_path(@post), alert: "Access Denied" unless can? :edit, @post
  end

  def update
    redirect_to posts_path, alert: "access defined" unless can? :update, @post
    if @post.update(post_params(params))
      redirect_to post_path(@post)
      flash[:notice] = "Post updated"
    else
      render :edit
    end
  end

  def show
    @favourite    = @post.like_for(current_user)
    @comment      = Comment.new
  end

  def destroy
    redirect_to root_path, alert: "access defined" unless can? :destroy, @post
    @post.destroy
    redirect_to posts_path, notice: "Post Deleted"
  end

  def post_params(params)
    params.require(:post).permit([:title, :body, :category_id, :user_id])
  end

  def get_post
    @post   = Post.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    @user = User.find_by_email params[:email]

    if @user && @user.authenticate(params[:password])

      session[:user_id]   = @user.id
      redirect_to root_path, notice: "Logged in"

    else

      flash[:notice] = "Wrong email or password"
      render :new, notice: "Wrong Account or Password"

    end

  end

  def destroy
    session[:user_id]=nil
    redirect_to root_path, notice: "Logged out"
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :get_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params(params)
    if @user.save
      session[:user_id]=@user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update user_params

    else

    end
  end


  def user_params(params)
  params.require(:user).permit([  :first_name,
                                  :last_name,
                                  :email,
                                  :password,
                                  :password_confirmation])
  end

  def get_user
    @user   = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favourites/index.html.erb
<table>
  <% for favourite in @favourites %>
  <tr>
    <td>
       <%= link_to favourite.post.title, post_path(favourite.post)%>
    </td>
    <td>
      By : <%= favourite.post.user.get_full_name %>
    </td>
  </tr>
  <% end %>
</table>
<tr>
  <td class="pages">
      <%= paginate @favourites %>
  </td>
</tr>

app/views/posts/_post_form.html.erb
<%= @post.errors.full_messages.join() + " " %>

<%= form_for @post do |p| %>
<table class="post-table">
  <tr>
    <td>
      <%= p.text_field :title, placeholder: 'Post Title' %>
    </td>
  </tr>
  <tr>

  </tr>
  <tr>

    <td colspan="2">
      <%= p.text_area :body, placeholder: 'Your dreams; your fears' %>
    </td>
  </tr>
  <tr>
    <td>
      <%= p.collection_select(  :category_id, Category.all, :id, :title,
                                prompt: "Category") %>
    </td>
    <td>
      <%= p.submit %>
    </td>
  </tr>
</table>

<% end %>

app/views/posts/edit.html.erb
<%= render "post_form" %>

app/views/posts/index.html.erb
<%= form_tag posts_path, method: 'get' do%>
<p>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag :search, name: nil %>
</p>
<% end %>

<table>
  <% for post in @posts %>
  <tr>
    <td> <%= link_to post.title, post_path(post)%></td>
    <td> Created By: <%= post.user.get_full_name %></td>
  </tr>
  <% end %>
  <tr>
    <td class="pages">
        <%= paginate @posts %>
    </td>
  </tr>
</table>

app/views/posts/new.html.erb
<%= render "post_form" %>

app/views/posts/show.html.erb
<table>

  <tr>
    <th>
      title
    </th>
    <th>
      body
    </th>
    <th>
      category
    </th>
  </tr>

  <tr>
    <td>
      <%= @post.title %>
    </td>
    <td>
      <%= @post.body %>
    </td>
    <td>
      <% if @post.category %>
        <%= @post.category.title %>
        <% end %>
    </td>
  </tr>
  <tr>
    <td>
      <span> Created By: <%= @post.user.get_full_name %> </span>
    </td>
  </tr>
  <% if can?(:manage, @post) %>
  <tr>
    <td>
      <%= link_to 'Edit Post', edit_post_path(@post)%>
      <%= link_to 'Delete Post', post_path(@post), method: :delete, data: {confirm: 'Are you sure'} %>
    </td>
  </tr>
  <% end %>
  <tr>
    <td>
      <% if @favourite.present? %>
      <%= link_to 'Unfavourite', post_favourite_path(@post, @favourite), method: :delete%>
      <% else %>
      <%= link_to 'Favourite', post_favourites_path(@post), method: :post %>
      <% end %>
    </td>
  </tr>

</table>

<%= form_for [@post, @comment] do |f|%>

  <div class="add-comment">
    <%= @comment.errors.full_messages.join() %>
    <%= f.label :body, value: 'New Comment' %> <br>
    <%= f.text_area :body %> <br>
    <%= f.submit %>

  </div>

<% end %>

<table>
  <% @post.comments.each do |com| %>

    <tr>
      <td>
        <%= com.body %>
      </td>
      <td>
        By: <%= com.user.get_full_name %>
      </td>
    </tr>
    
    <% if can?(:manage, com) %>
    <tr>
      <td>
        <%= link_to 'Delete Comment' %>
      </td>
    </tr>
    <% end %>

  <% end %>
</table>

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>

<% end %>

<%= form_for @user do |f| %>
<table>

  <tr>
    <td>
      <%= f.label :first_name %>
    </td>
    <td>
      <%= f.text_field :first_name %>
    </td>
  </tr>

  <tr>
    <td>
      <%= f.label :last_name %>
    </td>
    <td>
      <%= f.text_field :last_name %>
    </td>
  </tr>

  <tr>
    <td>
      <%= f.label :email %>
    </td>
    <td>
      <%= f.email_field :email %>
    </td>
  </tr>
  <% if @user.new_record? %>
  <tr>
    <td>
      <%= f.label :password %>
    </td>
    <td>
      <%= f.password_field :password %>
    </td>
  </tr>
<tr>
  <td>
    <%= f.label :password_confirmation %>
  </td>
  <td>
    <%= f.password_field :password_confirmation %>
  </td>
</tr>
<% end %>
<tr>
  <td>
    <%= f.submit %>
  </td>
</tr>
  </table>
<% end %>

app/views/users/edit.html.erb
<%= render 'user_form' %>

app/views/users/new.html.erb
<%= render 'user_form' %>